* Improve qsub_sync: Get return value from command submitted by qsub.

diff --git a/trunk/qsub_sync b/trunk/qsub_sync
--- a/trunk/qsub_sync
+++ b/trunk/qsub_sync
@@ -1,12 +1,20 @@
 #!/bin/bash
+#
+#   This is a wrapper for qsub (of torque). It waits until the submitted
+# commands (from stdin) are finished on computational nodes, and provides
+# the return value from the last command. Also, it captures KILL signals
+# to stop the remote running tasks.
 
 RET=0
-JOB_ID=$(qsub -d $(pwd) -k n)
+STDOUT=$(mktemp)
+STDERR=$(mktemp)
+JOB_ID=$( (cat; echo ';echo $?') | qsub -d "$(pwd)" -o "${STDOUT}" -e "${STDERR}")
 
 function kill_job
 {
 	qdel ${JOB_ID}
-	exit 1
+	RET=1
+	exit ${RET}
 }
 trap kill_job INT
 trap kill_job ABRT
@@ -16,5 +24,8 @@ trap kill_job TERM
 while qstat ${JOB_ID} >/dev/null 2>/dev/null; do
 	sleep 5;
 done
-rm -f STDIN.{e,o}$(echo ${JOB_ID} | cut -d. -f1)
+
+RET=$(cat ${STDOUT})
+rm -f ${STDOUT} ${STDERR}
+
 exit ${RET}
